### ISSUE TITLE
error building arm64 mmal

### ISSUE THREAD

**Issue by anfederman** [6by9/userland#16]
[ 41%] Building C object host_applications/linux/libs/bcm_host/CMakeFiles/bcm_host.dir/__/__/__/__/interface/vmcs_host/linux/vcfilesys.c.o
In file included from /home/ubiq22/userland/build/inc/interface/vcos/vcos.h:144,
                 from /home/ubiq22/userland/interface/vmcs_host/linux/vcfilesys.c:56:
/home/ubiq22/userland/interface/vmcs_host/linux/vcfilesys.c: In function ‘vc_hostfs_totalspace64’:
/home/ubiq22/userland/build/inc/interface/vcos/vcos_logging.h:234:88: error: ‘%s’ directive argument is null [-Werror=format-overflow=]
  234 | _level, fmt...)   do { if (vcos_is_log_enabled(cat,_level)) vcos_log_impl(cat,_level,fmt); } while (0)

**Comment by anfederman** [comment]
I was successful in getting raspistill and Raspicam working on Ubuntu 20.04
ARM64.

I have not succeeded in 22.04. as a matter of fact, I can't even get V4L2
to work.
